# Generated by Django 5.2.9 on 2026-02-04 11:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='發票號碼')),
                ('buyer_id', models.CharField(max_length=8, verbose_name='買方統編')),
                ('seller_id', models.CharField(max_length=8, verbose_name='賣方統編')),
                ('date', models.DateField(verbose_name='發票日期')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='總金額')),
                ('invoice_type', models.CharField(choices=[('qr', 'QR'), ('paper', 'PAPER')], default='paper', max_length=10, verbose_name='發票類型')),
                ('category', models.CharField(choices=[('飲食', 'FOOD'), ('衣物', 'CLOTHING'), ('醫藥/衛生', 'MEDICAL'), ('住(租金/房貸)', 'HOUSING'), ('生活物品', 'HOUSEHOLD_GOODS'), ('行(交通費/油錢)', 'TRANSPORT'), ('教育(學費)', 'EDUCATION'), ('娛樂(場地門票)', 'ENTERTAINMENT'), ('理財', 'FINANCE'), ('發票中獎', 'WINNING'), ('其它', 'OTHER')], default='其它', max_length=20, verbose_name='主分類')),
                ('subcategory', models.CharField(blank=True, choices=[('vegetable', '菜錢'), ('drink', '飲料'), ('restaurant', '餐廳'), ('snack', '零食'), ('parking', '停車費'), ('gasoline', '油錢'), ('easy_card', '悠遊卡'), ('etag', 'eTag'), ('taxi', '計程車'), ('hsr', '高鐵票'), ('tra', '台鐵票'), ('water_electric', '水電'), ('gas_fee', '瓦斯'), ('internet', '電視網路'), ('phone', '手機/電話'), ('mortgage', '房貸'), ('management', '管理費'), ('sundries', '雜貨'), ('tissue', '衛生紙'), ('appliance', '電器品'), ('maintenance', '維修保養'), ('movie', '電影票'), ('ticket', '設施入場券'), ('fund', '基金'), ('stock', '股票'), ('gold', '黃金'), ('exchange', '換匯'), ('tax', '稅金'), ('fine', '罰款'), ('insurance', '保險'), ('delivery_family', '網購取件-全家'), ('delivery_711', '網購取件-7-11'), ('delivery_ok', '網購取件-OK'), ('delivery_hilife', '網購取件-萊爾富')], max_length=30, null=True, verbose_name='細分類')),
                ('owner', models.CharField(choices=[('familyUse', 'ALL'), ('father', 'FATHER'), ('mother', 'MOTHER'), ('child_1', 'CHILD_1'), ('child_2', 'CHILD_2'), ('child_3', 'CHILD_3')], default='familyUse', max_length=20, verbose_name='使用者')),
                ('raw_qr_data', models.JSONField(blank=True, null=True, verbose_name='QR原始資料')),
                ('raw_ocr_data', models.TextField(blank=True, null=True, verbose_name='OCR原始資料')),
                ('image', models.ImageField(blank=True, null=True, upload_to='invoices/%Y/%m/', verbose_name='發票圖片')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='已確認')),
                ('is_synced', models.BooleanField(default=False, verbose_name='已同步至 Sheets')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['number'], name='invoices_number_46af2b_idx'), models.Index(fields=['date'], name='invoices_date_17c1d6_idx'), models.Index(fields=['is_confirmed'], name='invoices_is_conf_255cc7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品名')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='單價')),
                ('category', models.CharField(blank=True, choices=[('飲食', '飲食'), ('衣物', '衣物'), ('醫藥/衛生', '醫藥/衛生'), ('住(租金/房貸)', '住(租金/房貸)'), ('生活物品', '生活物品'), ('行(交通費/油錢)', '行(交通費/油錢)'), ('教育(學費)', '教育(學費)'), ('娛樂(場地門票)', '娛樂(場地門票)'), ('理財', '理財'), ('發票中獎', '發票中獎'), ('其它', '其它')], max_length=20, null=True, verbose_name='品項分類')),
                ('sub_category', models.CharField(blank=True, choices=[('vegetable', '菜錢'), ('drink', '飲料'), ('restaurant', '餐廳'), ('snack', '零食'), ('parking', '停車費'), ('gasoline', '油錢'), ('easy_card', '悠遊卡'), ('etag', 'eTag'), ('taxi', '計程車'), ('hsr', '高鐵票'), ('tra', '台鐵票'), ('water_electric', '水電'), ('gas_fee', '瓦斯'), ('internet', '電視網路'), ('phone', '手機/電話'), ('mortgage', '房貸'), ('management', '管理費'), ('sundries', '雜貨'), ('tissue', '衛生紙'), ('appliance', '電器品'), ('maintenance', '維修保養'), ('movie', '電影票'), ('ticket', '設施入場券'), ('fund', '基金'), ('stock', '股票'), ('gold', '黃金'), ('exchange', '換匯'), ('tax', '稅金'), ('fine', '罰款'), ('insurance', '保險'), ('delivery_family', '網購取件-全家'), ('delivery_711', '網購取件-7-11'), ('delivery_ok', '網購取件-OK'), ('delivery_hilife', '網購取件-萊爾富')], max_length=30, null=True, verbose_name='細分類')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='domain.invoice', verbose_name='發票')),
            ],
            options={
                'db_table': 'items',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['invoice', 'order'], name='items_invoice_c15c4a_idx')],
            },
        ),
    ]
