# Generated by Django 5.2.9 on 2026-02-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
